---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli

inputs:
- name: app
- name: version
- name: pipelines

run:
  path: pipelines/cf/tasks/blue-green-deploy.sh
