build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

app_name: company-initial
jar_name: mstake-company

github_app_repo_uri: https://github.com/morganstakecgi/company-initial.git
github_app_repo_branch: master # don't change

github_pipelines_repo_uri: https://github.com/morganstakecgi/training-pipelines-initial.git
github_pipelines_repo_branch: master # don't change

version_bucket: cgi-ci
version_bucket_region_name: ""

version_key: mstake-company-version # set to '<first_initial><lastname>-company-version'.  ex: sgreenberg-company-version
initial_version: 0.0.1

artifact_regexp: mstake-company-(.*).jar # set to '<first_initial><lastname>-company-(.*).jar'.  ex: sgreenberg-company-(.*).jar
artifact_bucket: cgi-ci
artifact_bucket_region_name: ""

cf_dev_api: https://api.run.pivotal.io # set to cf api endpoint
cf_dev_organization: rscale-training-2 # set to your org
cf_dev_space: morgan.stake@cgi.com # set to your space
cf_dev_hostname: company-mstake # set to 'company-<first_initial><lastname>'. ex: company-sgreenberg
cf_dev_domain: cfapps.io # set to the apps domain for your CF
cf_dev_manifest: dev-manifest.yml # set to the dev manifest path in your company app repository. ex: dev-manifest.yml


s3_endpoint: http://10.144.88.117:9000